### ISSUE TITLE
Incluir tags para que el repo aparezca en Fiuba Repos

### ISSUE THREAD

**Issue by lima-limon-inc** [valenpontaut/ALGOII-tp2-104413#2]
Si anadis la tag de `fiuba` y las tags de la materia, el repo aparece en [Fiuba Repos](https://fede.dm/FIUBA-Repos). 

Hace que sea mas facil de encontrar! \:D/

Gracias Fede dm :place_of_worship:

**Comment by valenpontaut** [comment]
Genial!
